// this file is duplicated in `backend/src/constants/metadata` and `webapp/constants/metadata.js`
export const CATEGORIES_MIN = 1
export const CATEGORIES_MAX = 3

export const categories = [
  {
    icon: 'networking',
    id: 'cat1',
    slug: 'networking',
    name: 'networking',
  },
  {
    icon: 'home',
    id: 'cat2',
    slug: 'home',
    name: 'home',
  },
  {
    icon: 'energy',
    id: 'cat3',
    slug: 'energy',
    name: 'energy',
  },
  {
    icon: 'psyche',
    id: 'cat4',
    slug: 'psyche',
    name: 'psyche',
  },
  {
    icon: 'movement',
    id: 'cat5',
    slug: 'body-and-excercise',
    name: 'body-and-excercise',
  },
  {
    icon: 'balance-scale',
    id: 'cat6',
    slug: 'law',
    name: 'law',
  },
  {
    icon: 'finance',
    id: 'cat7',
    slug: 'finance',
    name: 'finance',
  },
  {
    icon: 'child',
    id: 'cat8',
    slug: 'children',
    name: 'children',
  },
  {
    icon: 'mobility',
    id: 'cat9',
    slug: 'mobility',
    name: 'mobility',
  },
  {
    icon: 'shopping-cart',
    id: 'cat10',
    slug: 'economy',
    name: 'economy',
  },
  {
    icon: 'peace',
    id: 'cat11',
    slug: 'peace',
    name: 'peace',
  },
  {
    icon: 'politics',
    id: 'cat12',
    slug: 'politics',
    name: 'politics',
  },
  {
    icon: 'nature',
    id: 'cat13',
    slug: 'nature',
    name: 'nature',
  },
  {
    icon: 'science',
    id: 'cat14',
    slug: 'science',
    name: 'science',
  },
  {
    icon: 'health',
    id: 'cat15',
    slug: 'health',
    name: 'health',
  },
  {
    icon: 'media',
    id: 'cat16',
    slug: 'it-and-media',
    name: 'it-and-media',
  },
  {
    icon: 'spirituality',
    id: 'cat17',
    slug: 'spirituality',
    name: 'spirituality',
  },
  {
    icon: 'culture',
    id: 'cat18',
    slug: 'culture',
    name: 'culture',
  },
  {
    icon: 'miscellaneous',
    id: 'cat19',
    slug: 'miscellaneous',
    name: 'miscellaneous',
  },
  {
    id: 'technology',
    slug: 'technology',
    name: 'technology',
    icon: 'cogs',
  },
  {
    id: 'music',
    slug: 'music',
    name: 'music',
    icon: 'music',
  },
  {
    id: 'art',
    slug: 'art',
    name: 'art',
    icon: 'pencil',
  },
  {
    id: 'crafts-trade',
    slug: 'crafts-trade',
    name: 'crafts-trade',
    icon: 'cubes',
  },
  {
    id: 'video',
    slug: 'video',
    name: 'video',
    icon: 'video-camera',
  },
  {
    id: 'photo',
    slug: 'photo',
    name: 'photo',
    icon: 'camera',
  },
  {
    id: 'podcast',
    slug: 'podcast',
    name: 'podcast',
    icon: 'microphone',
  },
  {
    id: 'sports',
    slug: 'sports',
    name: 'sports',
    icon: 'location-arrow',
  },
  {
    id: 'crypto',
    slug: 'crypto',
    name: 'crypto',
    icon: 'credit-card',
  },
  {
    id: 'space',
    slug: 'space',
    name: 'space',
    icon: 'rocket',
  },
  {
    id: 'environment',
    slug: 'environment',
    name: 'environment',
    icon: 'recycle',
  },
  {
    id: 'society',
    slug: 'society',
    name: 'society',
    icon: 'pie-chart',
  },
  {
    id: 'opinion',
    slug: 'opinion',
    name: 'opinion',
    icon: 'comments',
  },
  {
    id: 'education',
    slug: 'education',
    name: 'education',
    icon: 'graduation-cap',
  },
  {
    id: 'travel',
    slug: 'travel',
    name: 'travel',
    icon: 'globe',
  },
  {
    id: 'books',
    slug: 'books',
    name: 'books',
    icon: 'book',
  },
  {
    id: 'search',
    slug: 'search',
    name: 'search',
    icon: 'search',
  },
  {
    id: 'offer',
    slug: 'offer',
    name: 'offer',
    icon: 'share',
  },
  {
    id: 'demonstration',
    slug: 'demonstration',
    name: 'demonstration',
    icon: 'bullhorn',
  },
]
